version: '3'
services:
    mysql:
        image: mysql:5.7
        container_name: sf3_mysql
        volumes:
            - .docker/data/db:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: sf3
            MYSQL_USER: sf3
            MYSQL_PASSWORD: sf3

    php:
        build: .docker/php
        container_name: sf3_php
        ports:
          - 80:80
        volumes:
          - .docker/config/vhosts:/etc/apache2/sites-enabled
          - .:/home/wwwroot/sf3
        depends_on:
          - mysql

